const users = [
    {
        id: 0,
        name: "Malik",
        aboutMe: 'Я Front-end разработчик',
        status: "Double click me!",
        lookingForAJob: true,
        followed: false,
    },
    {
        id: 1,
        name: 'Billy',
        aboutMe: 'Доброта спасёт мир!!!',
        status: "Double click me!",
        lookingForAJob: true,
        followed: false,
    },
    {
        id: 2,
        name: 'Cameron',
        aboutMe: 'У меня вышел новый альбом!!!',
        status: "Double click me!",
        lookingForAJob: true,
        followed: false,
    },
    {
        id: 3,
        name: 'Adrianne',
        aboutMe: 'Каждый день прыгю с парашютом, присоединяйтесь',
        status: "Double click me!",
        lookingForAJob: true,
        followed: false,
    },
    {
        id: 4,
        name: 'Robert',
        aboutMe: 'Снял 3 фильма, из них 4 получили оскара :)',
        status: "Double click me!",
        lookingForAJob: false,
        followed: true,
    },
    {
        id: 5,
        name: 'Alan',
        aboutMe: 'Физкульт привет, кому составить план тренировок - пишите в личку',
        status: "Double click me!",
        lookingForAJob: true,
        followed: false,
    },
    {
        id: 6,
        name: 'Hugh',
        aboutMe: 'Бесконечность не предел !!!',
        status: "Double click me!",
        lookingForAJob: false,
        followed: true,
    },
    {
        id: 7,
        name: 'Amanda',
        aboutMe: 'Люблю рисовать, сегодня отличная погода для пейзажа',
        status: "Double click me!",
        lookingForAJob: false,
        followed: false,
    },
    {
        id: 8,
        name: 'Justin',
        aboutMe: 'Умение перелезать через заборы - показатель интеллекта',
        status: "Double click me!",
        lookingForAJob: false,
        followed: true,
    },
    {
        id: 9,
        name: 'Peter',
        aboutMe: 'С наступающим моим днём рождения ;)',
        status: "Double click me!",
        lookingForAJob: true,
        followed: true,
    },
    {
        id: 10,
        name: 'Max',
        aboutMe: 'Области тьмы один из лучших сериалов, всем советую!!!',
        status: "Double click me!",
        lookingForAJob: true,
        followed: true,
    },
    {
        id: 11,
        name: 'John',
        aboutMe: 'Так сладок мед, что, наконец, он горек. Избыток вкуса убивает вкус.',
        status: "Double click me!",
        lookingForAJob: true,
        followed: false,
    },
];

export default users;