const users = [
    {
        id: 0,
        name: "Malik",
        aboutMe: 'Я Front-end разработчик',
        status: "Double click me!",
        lookingForAJob: true,
        followed: false,
    },
    {
        id: 1,
        name: 'Billy',
        aboutMe: 'Я крутой',
        status: "Double click me!",
        lookingForAJob: true,
        followed: false,
    },
    {
        id: 2,
        name: 'Cameron',
        aboutMe: 'Я крутой',
        status: "Double click me!",
        lookingForAJob: true,
        followed: false,
    },
    {
        id: 3,
        name: 'Alex',
        aboutMe: 'Я крутой',
        status: "Double click me!",
        lookingForAJob: true,
        followed: false,
    },
    {
        id: 4,
        name: 'Billy',
        aboutMe: 'Я крутой',
        status: "Double click me!",
        lookingForAJob: true,
        followed: false,
    },
    {
        id: 5,
        name: 'Cameron',
        aboutMe: 'Я крутой',
        status: "Double click me!",
        lookingForAJob: true,
        followed: false,
    },
    {
        id: 6,
        name: 'Alex',
        aboutMe: 'Я крутой',
        status: "Double click me!",
        lookingForAJob: true,
        followed: false,
    },
    {
        id: 7,
        name: 'Billy',
        aboutMe: 'Я крутой',
        status: "Double click me!",
        lookingForAJob: true,
        followed: false,
    },
    {
        id: 8,
        name: 'Cameron',
        aboutMe: 'Я крутой',
        status: "Double click me!",
        lookingForAJob: true,
        followed: false,
    },
    {
        id: 9,
        name: 'Alex',
        aboutMe: 'Я крутой',
        status: "Double click me!",
        lookingForAJob: true,
        followed: false,
    },
    {
        id: 10,
        name: 'Billy',
        aboutMe: 'Я крутой',
        status: "Double click me!",
        lookingForAJob: true,
        followed: false,
    },
    {
        id: 11,
        name: 'Cameron',
        aboutMe: 'Я крутой',
        status: "Double click me!",
        lookingForAJob: true,
        followed: false,
    },
];

export default users;